# =========================
# RENDER POSTGRESQL CONFIG
# =========================

spring.datasource.url=jdbc:postgresql://dpg-d8r87bjeo5us73d1kfjg-a.oregon-postgres.render.com:5432/elite_events_yxf1
spring.datasource.username=elite_events_yxf1_user
spring.datasource.password=Ku7vooz9ntYJaPt0zY4lITA6ElNkUbCT
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA SETTINGS
# =========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect